### ISSUE TITLE
Support for SB X4 USB device?

### ISSUE THREAD

**Issue by scyto** [nicojeske/MasterVolumeSync#5]
I know you don't have one of these, so the answer is probably no :-)

I have an SB X4 for a different system.  I was hoping this might do the same as it does on the sound card.
It doesn't (which doesn't surprise me) - was hoping the sync was generic?

<img width="283" alt="image" src="https://user-images.githubusercontent.com/11369180/216795613-2f185944-b250-4a70-ad95-6c327b866f81.png">

**Comment by nicojeske** [comment]
To determine whether MasterVolumeSync is running properly, you can check the Mixer tab in Sound Blaster Command and observe whether the "What U Hear" and "Speakers" bars change as you adjust the volume. If they do change, it indicates that MasterVolumeSync is should be functioning correctly. 

Normally, the synchronization process should be generic since you can manually select the specific devices you want to sync. This means that, internally, the process treats all devices in the same way, only distinguishing between them through their unique device IDs. 

It could of course also be that the SB X4 somehow works differently, but if changing the volume of What-U-Hear manually in Sound Blaster Command changes your volume, MasterVolumeSync should also do it.

**Comment by scyto** [comment]
feature request requested https://community.home-assistant.io/t/add-hyper-v-guest-services-to-hyper-v-vhdx-image-to-support-standard-and-production-snapshots/542154

**Comment by scyto** [comment]
I had tested before i posted, it wasn't working, hence the ask.
It doesn't use SB command it uses a different app, so i think this just confirms this is not a simple issue.
