### ISSUE TITLE
03/2024 Version 1.09 No more running

### ISSUE THREAD

**Issue by LxRmp** [nicojeske/MasterVolumeSync#9]
Hi,

First of all thanks for your app.
Unfortunately in the last few weeks the version 1.09 stopped working for me.
Before was working fine, but now when I launch the compiled .exe file aftrer instrallation it doesn't start (not even ask for admin confirmation).

When I try to launch the app by building the project in VisualStudio this error appear:

![image](https://github.com/nicojeske/MasterVolumeSync/assets/164091387/78c09f38-ca2d-4610-a041-9bb633879a28)

![image](https://github.com/nicojeske/MasterVolumeSync/assets/164091387/b2b13d71-5283-4f03-a210-cbc6027c6387)

It's seems to be happen right after I moved the soundblaster ZSE from a PCIE 3 to a PCIE 4 port on my MB, Could this be the cause of the issue?
Other than that the only other changes to my PC were the windows 11 updates.

Please let me know if I'm missing smothing or if there is a solution.

Thanks and regards

**Comment by nicojeske** [comment]
There seems to be a problem with NAudio, the library I use to get current volume level, as it does not seem to be able to recognize  that the soundcard is actually an audio output. 

Maybe the device ID changed because of you moving the card to another PCIE port. For that you can try to edit the file `Settings.json` in `C:\Users\<yourUserName>\AppData\Local\MasterVolumeSync` and remove `"OutputId": "{<deviceId>}",`. When you then start the app it will automatically select the default output device.

**Comment by LxRmp** [comment]
Hi, 

Thank you very much for pointing me in the right direction.
I've tried as you said but was not working (error on the format of the .json file) 
So to try again I completely deleted the .json file from the folder and... et voilà!! after the first launch the file was recreated with the correct address and now is working fine.

Again thank you for your work and your support.

**Comment by nicojeske** [comment]
Nice to hear, that it works again!
